### ISSUE TITLE
Update Elasticsearch to image version 7.17.27

### ISSUE THREAD

**Issue by MichaelThumes** [RotherOSS/otobo#4035]
[Edit sha]
Original title: ElasticSearch container unhealthy with Kernel version equal or greater 6.12 and systemd equal or greater version 256
[End Edit]

### tl;dr:

Please consider upgrading the otobo-docker Elastic-Search container to latest patchlevel (7.17.26 at time of writing)

### Environment

- Server OS Distribution:Ubuntu 24.10 + Kernel 6.12
- OTOBO installation typ: Docker
- Browser: n/a
- OTOBO version: rel-10_0 through rel -11_1

The crucial point here is the version of the ElasticSearch docker image used, which currently is the same **7.17.3** for all otobo release branches.

### Expected behavior

ElasticSearch container starts up and is reported 'healthy' after initial 'starting health' phase.

### Actual behavior

ElasticSearch container runs into a fatal exception during JVM initialization that kills the JVM and results in a 'docker container unhealthy - restarting' endless loop when run under Kernel >= 6.12 with systemd >= 256.

The issue can be pinned down by looking for a specific fatal exception in the elasticsearch container logs:

docker logs otobo-elastic-1
```
FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'
2024-12-24 12:10:10,821 main ERROR Could not reconfigure JMX java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
    at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:80)
    at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:114)
    at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:177)
    at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
    at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
    at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
    at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
```

This is an error involving the JVM interface to the Kernel cgroups feature. See Additional Information below for details.

### How to reproduce

The problem can be replicated using standard Ubuntu 24.10 (which comes with systemd 256) and manually upgrading the kernel to 6.12 (standard Ubuntu kernel  for 24.10 at time of writing is 6.11, which does **NOT** exhibit the problem).

On a virtualised (eg virtualbox) fresh install of Ubuntu 24.10, guest additions installed, with apt upgrade & update the system reports Kernel 6.11 and systemd 256:
```
mike@mike-u2410:~$ uname -a
Linux mike-u2410 6.11.0-13-generic RotherOSS/otobo-docker#14-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov 30 23:51:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

mike@mike-u2410:~$ systemctl --version
systemd 256 (256.5-2ubuntu3.1)
```
With this scenario, ElasticSearch container still starts fine. 

However manually **upgrading the Kernel to 6.12 triggers the same JVM fatal exception** like we first saw on Arch Linux.

There are official stable Ubuntu Kernels with v 6.12 from early December 2024, to install:
```
cd /tmp
wget -c https://kernel.ubuntu.com/mainline/v6.12.3/amd64/linux-headers-6.12.3-061203_6.12.3-061203.202412060638_all.deb
wget -c https://kernel.ubuntu.com/mainline/v6.12.3/amd64/linux-headers-6.12.3-061203-generic_6.12.3-061203.202412060638_amd64.deb
wget -c https://kernel.ubuntu.com/mainline/v6.12.3/amd64/linux-image-unsigned-6.12.3-061203-generic_6.12.3-061203.202412060638_amd64.deb
wget -c https://kernel.ubuntu.com/mainline/v6.12.3/amd64/linux-modules-6.12.3-061203-generic_6.12.3-061203.202412060638_amd64.deb
sudo dpkg -i *.deb
sudo reboot
```

**Note**: Errors/Warnings during DKMS update for virtual-box guest additions can be ignored for this test scenario. You are doing this on a throw-away VM anyway, do you?

After reboot, the ElasticSearch container will now go into the **'unhealthy'** restart loop and logs show the JVM exception from above. 

_Bingo_.

Until proven otherwise, assumption is this behavior will also surface for other distros besides Ubuntu and Arch Linux, once their respective mainline reaches Kernel version 6.12 in combination with systemd v256. 

### Potential Impact

Customers running existing otobo installations with ElasticSearch are in risk of breaking their ElasticSearch functionality when doing a plain system upgrade of the Host system that happens to upgrade Kernel to >= v6.12 and systemd >= 256.

### Possible Mitigation

Upgrading the ElasticSearch container from 7.17.3 to latest patchlevel 7.17.26 seems to solve the issue.

Steps to reproduce mitigation:

This requires local build of ES docker container. Clone the main otobo repository and patch the otobo.elasticsearch.dockerfile as follows:

```
-FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.3 AS  otobo-elasticsearch
+FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.26 AS otobo-elasticsearch
``` 

then build the ES docker image only in your otobo root folder - for your current release version (here: rel-10_1):
```
export DOCKERFILE_PATH=../../otobo.elasticsearch.dockerfile
export IMAGE_NAME=otobo-elasticsearch:local-rel-10_1
export BUILD_PATH=scripts/elasticsearch
hooks/build
```

then patch your local otobo-docker folder .env file to use the local ES build (note: use version according to your current build):
```
# uncomment and patch:
OTOBO_IMAGE_OTOBO_ELASTICSEARCH=otobo-elasticsearch:local-rel-10_1
```

Restarting the containers makes the JVM error go away and the ES container is again reported as healthy.

### Backward Compat Considerations

An experimental install of legacy Ubuntu 20.04 LTS did not exhibit the bug as expected (lower kernel and systemd versions).
However patching the ES docker image to use latest patch level as above did not harm and ES container is still reported healthy.

Conclusion would be that upgrading should not harm existing legacy installations, but this might need further proofing (what is current baseline? Is Ubuntu 18.04 still supported? Debian? Fedora?)

**Note**: Evaluating feasibility of upgrading to a new major ES docker container version was considered outside the scope of this exercise. New major version 8.x.x already exists at time of writing, but that possibly would require further acceptance testing?

### Additional information

The issue first surfaced in early Dec 2024 when Arch Linux updated to Kernel 6.12, triggering a new behavior in systemd (with systemd version >= 256) which disables the legacy 'cgroups V1' feature.  The replacement V2 feature is avail for almost a decade and since vanilla kernel 4.5. It is systemd v256+ that will enforce V2 by disabling the V1 kernel feature starting with Kernel v6.12.

Systemd github issue tracked down by @stefanhaerter :
https://github.com/systemd/systemd/issues/30852

Stackoverflow:
https://stackoverflow.com/questions/71532170/java-lang-nullpointerexception-cannot-invoke-jdk-internal-platform-cgroupinfo/71585718#71585718

>This helped in my case. Arch recently updated to 6.12. I had suspected it could be related to a Docker update but not the kernel. It would have taken me into a very deep rabbit hole to troubleshoot this myself. Thank you! –
>Anthony
>Commented Dec 3 at 13:32

Arch wiki:
https://wiki.archlinux.org/title/Cgroups - see section 7.1 at bottom of page

Wikipedia Cgroups:
https://en.wikipedia.org/wiki/Cgroups

### Screenshots
n/a

**Comment by bschmalhofer** [comment]
I set the milestone to 10.0 as all versions are affected.

**Comment by bschmalhofer** [comment]
Another thought, primarily for OTOBO 11.1.x.  The reason for having an OTOBO specific ElasticSearch image is the use of two plugins.
```
# Install important plugins
RUN bin/elasticsearch-plugin install --batch ingest-attachment
RUN bin/elasticsearch-plugin install --batch analysis-icu

```
It might simplify things if we could find an image that already contains these plugins.

**Comment by stefanhaerter** [comment]
@MichaelThumes Thank you very much for testing and organizing the information!

**Comment by stefanhaerter** [comment]
I did a small bit of further research. According to [Distrowatch systemd](https://distrowatch.com/dwres.php?resource=package-in-distro&pkg=systemd), the following - potentially OTOBO-relevant - distros and versions should be affected (at time of writing):

- Debian
    - testing
    - unstable
- RHEL (RedHat Enterprise Linux)
    - RHEL-10.0-beta
- Ubuntu
    - snapshot
    - 24.10

**Comment by stefanhaerter** [comment]
Transferred issue to core repository as the file in question (`otobo.elasticsearch.dockerfile`) is part of core.

**Comment by stefanhaerter** [comment]
Created https://github.com/RotherOSS/otobo/pull/4085 as base for discussion.

**Comment by stefanhaerter** [comment]
Decision in a meeting was to also add a minimal unit test, which activates elasticsearch, creates a ticket with an attachment and tests if the ticket is searchable via elasticsearch.

**Comment by stefanhaerter** [comment]
For the records: the change of ES image version in #4085 does indeed solve the problem.

**Comment by stefanhaerter** [comment]
Closing the issue with #4085 merged, which includes a simple unit test for elasticsearch.
